CREATE TABLE `ai_agents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`nameRu` varchar(100),
	`slug` varchar(50) NOT NULL,
	`description` text,
	`descriptionRu` text,
	`type` enum('code','research','writing','planning','analysis','general') NOT NULL,
	`capabilities` json,
	`systemPrompt` text,
	`modelPreference` varchar(50),
	`fallbackModel` varchar(50),
	`temperature` int DEFAULT 70,
	`maxTokens` int DEFAULT 4096,
	`triggerPatterns` json,
	`priority` int DEFAULT 0,
	`isActive` boolean DEFAULT true,
	`isSystem` boolean DEFAULT false,
	`totalRequests` int DEFAULT 0,
	`avgResponseTime` int DEFAULT 0,
	`successRate` int DEFAULT 100,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ai_agents_id` PRIMARY KEY(`id`),
	CONSTRAINT `ai_agents_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `ai_integrations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`provider` varchar(50) NOT NULL,
	`displayName` varchar(100),
	`apiKey` text,
	`accessToken` text,
	`refreshToken` text,
	`tokenExpiresAt` timestamp,
	`config` json,
	`isActive` boolean DEFAULT true,
	`lastUsedAt` timestamp,
	`lastErrorAt` timestamp,
	`lastError` text,
	`totalRequests` int DEFAULT 0,
	`totalTokens` int DEFAULT 0,
	`totalCost` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ai_integrations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ai_request_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`requestType` enum('chat','generate','skill','mcp') NOT NULL,
	`agentId` int,
	`skillId` int,
	`mcpServerId` int,
	`input` text,
	`output` text,
	`model` varchar(64),
	`provider` varchar(50),
	`tokensUsed` int,
	`responseTimeMs` int,
	`status` enum('success','error','timeout','rate_limited') DEFAULT 'success',
	`errorMessage` text,
	`creditsCost` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ai_request_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ai_skills` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`nameRu` varchar(100),
	`slug` varchar(50) NOT NULL,
	`description` text,
	`agentId` int,
	`triggerPatterns` json,
	`handlerType` enum('prompt','function','mcp','webhook') DEFAULT 'prompt',
	`handlerConfig` json,
	`inputSchema` json,
	`outputSchema` json,
	`isActive` boolean DEFAULT true,
	`isSystem` boolean DEFAULT false,
	`totalInvocations` int DEFAULT 0,
	`avgExecutionTime` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ai_skills_id` PRIMARY KEY(`id`),
	CONSTRAINT `ai_skills_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `mcp_servers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`slug` varchar(50) NOT NULL,
	`description` text,
	`endpoint` varchar(500) NOT NULL,
	`protocol` enum('stdio','http','websocket') DEFAULT 'http',
	`authType` enum('none','api_key','oauth','basic') DEFAULT 'none',
	`authConfig` json,
	`tools` json,
	`status` enum('active','inactive','error','connecting') DEFAULT 'inactive',
	`lastHealthCheck` timestamp,
	`lastError` text,
	`totalRequests` int DEFAULT 0,
	`avgResponseTime` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mcp_servers_id` PRIMARY KEY(`id`),
	CONSTRAINT `mcp_servers_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `orchestrator_config` (
	`id` int AUTO_INCREMENT NOT NULL,
	`routingRules` json,
	`fallbackAgentId` int,
	`fallbackModel` varchar(50) DEFAULT 'gpt-4o-mini',
	`loggingLevel` enum('debug','info','warn','error') DEFAULT 'info',
	`logRetentionDays` int DEFAULT 30,
	`globalRateLimit` int DEFAULT 100,
	`enableAgentRouting` boolean DEFAULT true,
	`enableSkillMatching` boolean DEFAULT true,
	`enableMCPIntegration` boolean DEFAULT true,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `orchestrator_config_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `subscription_plans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`nameRu` varchar(100),
	`slug` varchar(50) NOT NULL,
	`price` int NOT NULL DEFAULT 0,
	`currency` varchar(3) DEFAULT 'USD',
	`billingPeriod` enum('monthly','yearly','lifetime') DEFAULT 'monthly',
	`creditsPerMonth` int NOT NULL DEFAULT 1000,
	`features` json,
	`maxProjects` int DEFAULT 3,
	`maxAiRequests` int DEFAULT 100,
	`maxTeamMembers` int DEFAULT 1,
	`allowedIntegrations` json,
	`isActive` boolean DEFAULT true,
	`isPopular` boolean DEFAULT false,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `subscription_plans_id` PRIMARY KEY(`id`),
	CONSTRAINT `subscription_plans_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `user_subscriptions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`planId` int NOT NULL,
	`status` enum('active','cancelled','expired','past_due','trialing') DEFAULT 'active',
	`stripeCustomerId` varchar(255),
	`stripeSubscriptionId` varchar(255),
	`startDate` timestamp NOT NULL DEFAULT (now()),
	`endDate` timestamp,
	`cancelledAt` timestamp,
	`trialEndsAt` timestamp,
	`currentPeriodStart` timestamp,
	`currentPeriodEnd` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `user_subscriptions_id` PRIMARY KEY(`id`)
);
